# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  cloud:
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout
      uses: actions/checkout@v2.4.2
    - name: Setup Node.js environment
      uses: actions/setup-node@v3.4.1
    - name: Install Canvas
      run: npm i canvas
    - name: Run
      run: node /src/main/resources/assets/cloudtech/textures/item/cloud
    - name: Upload
      uses: actions/upload-artifact@v3.1.0
      with:
        name: cloud
        path: /src/main/resources/assets/cloudtech/textures/item
    
